services:
  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: "Asia/Kolkata"
      WEBPASSWORD: "password"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: 172.20.0.100

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: pihole_watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
