services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3030:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=your_super_strong_random_secret_here # Generate: openssl rand -base64 32
      # Optional: Match your host user for permissions
      - PUID=2000
      - PGID=2000
      # Optional: Set if Docker access fails
      # - DOCKER_GID=998
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped

volumes:
  arcane-data:
    driver: local
