

services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      # Exposes the web UI on port 8787 of your host machine.
      - "8787:80"
      - "8743:443"
    volumes:
      # This local directory will store all application data,
      # including the SQLite database file.
      - ./config:/config
    environment:
      # All environment variables are loaded from the .env file.
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - APP_KEY=MMfxmfVXlYWUB06l779Sbj9MPvtXLTNj5ELXhOzxDvQ=
      - APP_NAME="Speedtest Tracker"
      - SPEEDTEST_SCHEDULE="0 * * * *"
      - PRUNE_RESULTS_OLDER_THAN=90
      - DB_CONNECTION=sqlite
