services:
  portainer:
    image: portainer/portainer-ce:2.24.0
    container_name: portainer
    restart: always
    ports:
      - "8081:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:9000/api/status"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 40s

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: portainer_watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup

volumes:
  portainer_data:
