services:
  mariadb:
    image: mariadb:lts-ubi9
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOSTS: mariadb, mysql
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 2G
    ports:
      - "8080:80"

    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data:
  mysql_data:
